apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-generator
  namespace: apps
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: grafana/k6:latest
          command: ["k6", "run", "/scripts/test.js"]
          env:
            - name: TARGET_URL
              value: "http://sample-app.apps.svc.cluster.local"
          volumeMounts:
            - name: script
              mountPath: /scripts
      volumes:
        - name: script
          configMap:
            name: k6-script